name: Semgrep Security Check

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - .github/workflows/semgrep.yml

jobs:
  semgrep:
    name: semgrep/scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_ENABLE_VERSION_CHECK: false

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep Full Scan on main
        if: github.event.pull_request.base.ref == 'main'
        run: semgrep --config=p/ci --error . --sarif --output=semgrep.sarif

      - name: Run Semgrep Diff Scan on other branches
        if: github.event.pull_request.base.ref == 'development'
        run: semgrep --config=p/ci --error --sarif --output=semgrep.sarif

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
