name: Semgrep Source Code Security Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - development

jobs:
  semgrep:
    name: Semgrep/ci Security Checks
    runs-on: ubuntu-latest
    container: semgrep/semgrep

    if: github.actor != 'dependabot[bot]'
    steps:
      - env:
          SEMGREP_ENABLE_VERSION_CHECK: false
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - uses: actions/checkout@v4
      - run: |
          semgrep ci
