name: Semgrep

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - development
      - master
    paths:
      - .github/workflows/semgrep.yml

jobs:
  semgrep:
    name: semgrep/scan
    runs-on: ubuntu-latest

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config="auto"
